<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Philiprehberger.ValueOf</PackageId>
    <Version>0.2.0</Version>
    <Authors>Philip Rehberger</Authors>
    <Description>Strongly-typed value objects with built-in validation and JSON support — eliminate primitive obsession.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>package-card.png</PackageIcon>
    <PackageTags>value-object;ddd;strong-typing;primitive-obsession;type-safe</PackageTags>
    <RepositoryUrl>https://github.com/philiprehberger/dotnet-value-of</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\package-card.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
